version: '3.9'

networks:
  transcendence:


services:
  backend:
    image: mcr.microsoft.com/devcontainers/typescript-node
    working_dir: /workspace/backend
    command: sh -c "npm install && npx prisma migrate dev && npx prisma db seed && npm run start:dev"
    container_name: backend
    networks:
      - transcendence
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node
    working_dir: /workspace/frontend
    command: sh -c "npm install && npm run dev"
    container_name: frontend
    networks:
      - transcendence
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - transcendence
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "5050:8080"
    networks:
      - transcendence
    depends_on:
      - db

volumes:
  db:
    driver: local
